---
cidr_networks:
  container: __NETWORK_BASE__.236.0/22
  tunnel: __NETWORK_BASE__.240.0/22
  storage: __NETWORK_BASE__.244.0/22

used_ips:
  - "__NETWORK_BASE__.236.0,__NETWORK_BASE__.236.200"
  - "__NETWORK_BASE__.240.0,__NETWORK_BASE__.240.200"
  - "__NETWORK_BASE__.244.0,__NETWORK_BASE__.244.200"
  - "__NETWORK_BASE__.248.0,__NETWORK_BASE__.248.200"

global_overrides:
  internal_lb_vip_address: __NETWORK_BASE__.236.150
  # The external IP is quoted simply to ensure that the .aio file can be used as input
  # dynamic inventory testing.
  external_lb_vip_address: "__HOSTIP__"
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-flat"
        container_type: "veth"
        container_interface: "eth12"
        type: "flat"
        net_name: "flat"
        group_binds:
          - neutron_linuxbridge_agent
          - utility_all
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "1:1"
        net_name: "vlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          - swift_proxy

haproxy_hosts:
  loadbalancer1:
    ip: __NETWORK_BASE__.236.150
